config/routes.rb
Rails.application.routes.draw do
  root 'posts#index'

  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  delete '/logout' => 'sessions#destroy'

  get '/signup' => 'users#new'
  post '/signup' => 'users#create'
  resources :users, only: [:show]
  resources :posts, only: [:new, :create]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user

  validates :title, length: { minimum: 5, maximum: 75 }, presence: true
  validates :body, length: { minimum: 5, maximum: 2000 }, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  attr_accessor :remember_token

  has_many :posts

  before_save :downcase_email

  has_secure_password

  validates :name, length: { minimum: 5, maximum: 25 }, presence: true
  validates :password, length: { minimum: 8, maximum: 50 }, presence: true
  VALID_EMAIL_REGEX = /\A([\w+\-].?)+@[a-z\d\-]+(\.[a-z]+)*\.[a-z]+\z/i
  validates :email, length: { maximum: 255 }, presence: true, format: { with: VALID_EMAIL_REGEX }, uniqueness: { case_sensitive: false }

  def authenticated?(attribute, token)
    digest = self.send("#{attribute}_digest")
    return false if digest.nil?
    BCrypt::Password.new(digest).is_password?(token)
  end

  def new_remember_token
    self.remember_token = User.new_token
    update_attribute(:remember_digest, User.digest(remember_token))
  end

  def clear_remember_digest
    update_attribute(:remember_digest, nil)
  end

  def User.new_token
    SecureRandom.urlsafe_base64
  end

  def User.digest string
    cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
                                              BCrypt::Engine.cost
    BCrypt::Password.create(string, cost: cost)
  end

  private
    def downcase_email
      self.email.downcase!
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include SessionsHelper
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :valid_user, only: [:new, :create]

  def index
    @posts = Post.all
  end

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)
    if @post.save
      flash[:success] = "Post created."
      redirect_to root_url
    else
      flash[:danger] = "Please try again."
      render 'new'
    end
  end

  private
    def post_params
      params[:post][:user_id] = current_user.id
      params.require(:post).permit(:title, :body, :user_id)
    end

    def valid_user
      unless current_user
        flash[:danger] = "You must be a member to do that."
        redirect_to root_url
      end
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new

  end

  def create
    @user = User.find_by(email: params[:session][:email])
    if @user && @user.authenticate(params[:session][:password])
      params[:session][:remember] ? remember(@user) : forget(@user)
      log_in(@user)
      redirect_to @user
    else
      flash.now[:danger] = "Password or email was incorrect."
      render 'new'
    end
  end

  def destroy
    log_out if logged_in?
    redirect_to root_url
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      flash[:success] = "Succesfully registered!"
      log_in(@user)
      redirect_to @user
    else
      flash.now[:danger] = "Please try again"
      render 'new'
    end
  end

  def show
    @user = User.find(params[:id])
  end

  private
    def user_params
      params.require(:user).permit(:name, :email, :password, :password_confirmation)
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper

  def log_in(user)
    session[:user_id] =  user.id
  end

  def log_out
    forget(current_user)
    session.delete(:user_id)
    @current_user = nil
  end

  def current_user
    if user_id = session[:user_id]
      @current_user ||= User.find_by(id: user_id)
    elsif user_id = cookies.signed[:user_id]
      user = User.find_by(id: user_id)
      if user && user.authenticated?(:remember, cookies[:remember_token])
        log_in user
        @current_user = user
      end
    end
  end

  def logged_in?
    !current_user.nil?
  end

  def remember(user)
    user.new_remember_token
    cookies.permanent.signed[:user_id] = user.id
    cookies.permanent[:remember_token] = user.remember_token
  end

  def forget(user)
    user.clear_remember_digest
    cookies.delete :user_id
    cookies.delete :remember_token
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_flash.html.erb
<% flash.each do |type, message| %>
  <%= type.capitalize + ": " + message %>
<% end %>

app/views/layouts/_header.html.erb
<%= link_to "Home", root_path %>
<% if current_user %>
  <%= link_to "New post", new_post_path %>
  <%= link_to "Profile", current_user %>
  <%= link_to "Log out", logout_url, method: 'delete' %>
<% else %>
  <%= link_to "Sign up", signup_path %>
  <%= link_to "Log in", login_path %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Members Only</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/header' %><br>
    <%= render 'layouts/flash' %>
    <%= yield %>
  </body>
</html>

app/views/posts/_post.html.erb
<div class="post">
  <h2><%= post.title %></h2>
  <% if current_user %>
    <i><%= User.find(post.user_id).name %></i>
  <% end %>
  <p><%= post.body %></p>
  <hr>
</div>

app/views/posts/index.html.erb
<h1>Posts</h1>

<ul>
  <%= render @posts %>
</ul>

app/views/posts/new.html.erb
<h1>New post</h1>

<%= form_for(@post) do |f| %>
  <%= f.label :title %><br>
  <%= f.text_field :title %><br>
  <%= f.label :body %><br>
  <%= f.text_area :body, size: '60x20' %><br>
  <%= f.submit "Submit" %>
<% end %>

app/views/users/new.html.erb
<h1>Sign up</h1>
<%= form_for(@user, url: signup_url) do |f| %>
  <%= f.label :name %><br>
  <%= f.text_field :name %><br>
  <%= f.label :email %><br>
  <%= f.email_field :email %><br>
  <%= f.label :password %><br>
  <%= f.password_field :password %><br>
  <%= f.label :password_confirmation %><br>
  <%= f.password_field :password_confirmation %><br>
  <%= f.submit "Sign up" %>
<% end %>

app/views/users/show.html.erb
<h1>Hi <%= @user.name %></h1>